# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.

obj-y += tpkits.o
tpkits-objs += huawei_ts_kit_core.o huawei_ts_kit_fsnode.o huawei_ts_kit_api.o huawei_ts_kit_algo.o huawei_ts_kit_csvparse.o

obj-y += huawei_tp_common.o
obj-y  += panel/
